name: "GitHub Followers Tracker"

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 10 * * *"

jobs:
  bot:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'

    - name: Install NPM dependancies
      run: npm install

    - name: Run code
      run: node index
      env:
        GIST_ID: ${{ secrets.GIST_ID }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
